### ISSUE TITLE
vdo command occurs error

### ISSUE THREAD

**Issue by narangel** [dm-vdo/vdo#13]
I installed vdo and kvdo on CentOS 7.5.
There are some error message as below.

[root@localhost vdo]# vdo
Traceback (most recent call last):
  File "/usr/bin/vdo", line 146, in <module>
    main()
  File "/usr/bin/vdo", line 111, in main
    arguments.logfile, arguments.debug)
AttributeError: 'Namespace' object has no attribute 'logfile'
[root@localhost vdo]#

[root@localhost vdo]# vdo create --name vdo0 --device=/dev/sdb --verbose
Creating VDO vdo0
    grep MemAvailable /proc/meminfo
    pvcreate -qq --test /dev/sdb
    modprobe kvdo
    vdoformat --uds-checkpoint-frequency=0 --uds-memory-size=0.25 /dev/disk/by-id/scsi-3600605b00d22397022b1ce98bec63b11
vdo: ERROR - vdoformat: formatVDO failed on '/dev/disk/by-id/scsi-3600605b00d22397022b1ce98bec63b11': VDO Status: Exceeds maximum number of slabs supported
[root@localhost vdo]#

What should I do to fix this..?

**Comment by drckeefe** [comment]
The default slab size is 2GB for VDO.  VDO requires a minimum of 2 slabs per volume and a maximum of 8192.  If you multiply the maximum number of slabs by the slab size, the result is the largest VDO physical storage for that slab size.  Looking at your output, you are trying to create a VDO volume on physical storage larger than 16TB.  Either increase the slab size with the --vdoSlabSize= option or decrease the physical storage size.  I would recommend using 32G. Note: Minimum slab size is 128M, max is 32G.

**Comment by drckeefe** [comment]
"[root@localhost vdo]# vdo
Traceback (most recent call last):
File "/usr/bin/vdo", line 146, in 
main()
File "/usr/bin/vdo", line 111, in main
arguments.logfile, arguments.debug)
AttributeError: 'Namespace' object has no attribute 'logfile'"

This has been fixed.
We're working to schedule our next update to github.  We expect it to come through soon.

**Comment by narangel** [comment]
I tried to create with small disk, then I got another error output as below.

[root@node1 ~]# vdo create --name vdo1 --device=/dev/sdb
Creating VDO vdo1
Starting VDO vdo1
vdo: ERROR - Could not set up device mapper for vdo1
Removing VDO vdo1
Stopping VDO vdo1
vdo: ERROR - device-mapper: reload ioctl on vdo1  failed: Input/output error
[root@node1 ~]#


And below is the "/var/log/messages" at that time.

Jun 15 10:37:44 node1 kernel: kvdo1:dmsetup: starting device 'vdo1' device instantiation 1 write policy auto
Jun 15 10:37:44 node1 kernel: kvdo1:dmsetup: underlying device, REQ_FLUSH: supported, REQ_FUA: not supported
Jun 15 10:37:44 node1 kernel: kvdo1:dmsetup: Using mode async automatically.
Jun 15 10:37:44 node1 kernel: kvdo1:dmsetup: zones: 1 logical, 1 physical, 1 hash; base threads: 5
Jun 15 10:37:44 node1 kernel: kvdo1:dmsetup: release version 133524 requires an upgrade: kvdo: Unsupported component version (2058)
Jun 15 10:37:44 node1 kernel: kvdo1:dmsetup: Could not create kernel physical layer. (VDO error 2058, message Could not load geometry block)
Jun 15 10:37:44 node1 kernel: kvdo1:dmsetup: mapToSystemError: mapping internal status code 2058 (kvdo: VDO_UNSUPPORTED_VERSION: kvdo: Unsupported component version) to EIO
Jun 15 10:37:44 node1 kernel: device-mapper: table: 253:3: vdo: Could not load geometry block
Jun 15 10:37:44 node1 kernel: device-mapper: ioctl: error adding target to table
Jun 15 10:37:44 node1 vdo: ERROR - Could not set up device mapper for vdo1
Jun 15 10:37:44 node1 vdo: ERROR - device-mapper: reload ioctl on vdo1  failed: Input/output error

Waht is wrong on this?

**Comment by bgurney-rh** [comment]
Please run "modinfo kvdo" to check the version of the kernel module, and "vdoformat --version" to check the version of the vdoformat program, which is used to format the block device (as part of the "vdo create" command).

What I believe has happened is that the "vdoformat" program you currently have installed is version 6.2.0 (manually installed), but the kvdo kernel module is version 6.1.0 (from CentOS 7.5's package repository).
