### ISSUE TITLE
Recover data from VDO after OS reinstall

### ISSUE THREAD

**Issue by sudhakar009** [dm-vdo/vdo#14]
Hi there, I have created 2 vdo devices (/dev/mapper/vdo1, /dev/mapper/vdo2) on 2 physical devices (/dev/sdc, /dev/sdd).
- created Logical Volume(vdo_lvm) on 2 vdo devices.
- Now my system crashed and reinstalled OS.
Can anyone know how to recover data from logical volume (vdo_lvm) ?

in my case i'm unable to find vdo devices, vgexport, no data.

**Comment by bgurney-rh** [comment]
When you say "my system crashed and reinstalled OS", I'm guessing that the "/etc/vdoconf.yml" file from the old instance was not copied into the new installation.

When you created /dev/mapper/vdo1 and /dev/mapper/vdo2, were there any additional switches used?  Specifically, did you use a non-default index size ("--indexMem" or "--sparseIndex" options), or a non-default slab size ("--vdoSlabSize" option)?

You can read the base configuration parameters using the "vdodumpconfig <device>" command.  I have an example with two test partitions:

`Number  Start       End         Size        File system  Name  Flags
 1      2048s       209715199s  209713152s               pri
 2      209715200s  419430399s  209715200s               pri

# vdodumpconfig /dev/nvme0n1p1
VDOConfig:
  blockSize: 4096
  logicalBlocks: 52428800
  physicalBlocks: 26214144
  slabSize: 524288
  recoveryJournalSize: 32768
  slabJournalBlocks: 224
UUID: fdb8ce75-d53d-4a7b-b2a9-f0b1eb6ac523

# vdodumpconfig /dev/nvme0n1p2
VDOConfig:
  blockSize: 4096
  logicalBlocks: 78643200
  physicalBlocks: 26214400
  slabSize: 524288
  recoveryJournalSize: 32768
  slabJournalBlocks: 224
UUID: c56593b2-aec0-4e1a-a051-3f509c7aaa9e
`

There is an email on the vdo-devel public mailing list, titled "[Recreating config file from VDO device](https://www.redhat.com/archives/vdo-devel/2018-December/msg00004.html)", with more information on recreating the vdoconf.yml file.

**Comment by sudhakar009** [comment]
Hi Bryan Gurney, thank you for your previous response. Here i'm giving actual scenario that we are following, can you please help us to overcome this.

We have created 2 vdo devices(VDO_STU1, VDO_STU2) with external disks shared from VNX which is mpatha, mpathb.
We have created Volume Group (VG_VDO) and created LVM(LVM_VDO) on top of 2 vdo devices (VDO_STU1, VDO_STU2) and formated LVM with ext4 filesystem.
After that we exported Volume Group (VG_VDO) by following procedure.

After OS reinstallation is done we are facing below errors and unable to find  vdodumpconfig for Physical devices (mpatha, mpathb).
and we have copied backup of "/etc/vdoconf.yml" and started vdo device, unfortunately we are getting below errors.

[root@xxxxx566 by-id]# vdo start -a
Starting VDO VDO_STU2
vdo: ERROR - Could not set up device mapper for VDO_STU2
Starting VDO VDO_STU1
vdo: ERROR - Could not set up device mapper for VDO_STU1
vdo: ERROR - vdodumpconfig: allocateVDO failed for '/dev/disk/by-id/dm-uuid-mpath-360060160253140004a3c0455be07e611' with VDO Status: Bad magic number

[root@xxxxx566 by-id]# vdodumpconfig dm-uuid-mpath-3600601602531400004020ccdbd07e611
vdodumpconfig: allocateVDO failed for 'dm-uuid-mpath-3600601602531400004020ccdbd07e611' with VDO Status: Bad magic number
vdodumpconfig: Could not load VDO from 'dm-uuid-mpath-3600601602531400004020ccdbd07e611'
[root@xxxxx566 by-id]# vdodumpconfig /dev/disk/by-id/dm-uuid-mpath-3600601602531400004020ccdbd07e611
vdodumpconfig: allocateVDO failed for '/dev/disk/by-id/dm-uuid-mpath-3600601602531400004020ccdbd07e611' with VDO Status: Bad magic number
vdodumpconfig: Could not load VDO from '/dev/disk/by-id/dm-uuid-mpath-3600601602531400004020ccdbd07e611' 

VDO Creation : We have followed below steps to create VDO and LVM.

[root@xxxxx566 ~]# vdo create --name=VDO_STU1   --device=/dev/mapper/mpatha --vdoLogicalSize=500G
[root@xxxxx566 ~]# vdo create --name=VDO_STU2   --device=/dev/mapper/mpathb --vdoLogicalSize=500G  --force

[root@xxxxx566 ~]# vdo list
VDO_STU1
VDO_STU2

VG Creation :
[root@xxxxx566 ~]# vgcreate VG_VDO /dev/mapper/VDO_STU1 /dev/mapper/VDO_STU2
  Physical volume "/dev/mapper/VDO_STU1" successfully created.
  Physical volume "/dev/mapper/VDO_STU2" successfully created.
  Volume group "VG_VDO" successfully created
[root@xxxxx566 ~]# lvcreate -l 100%FREE -n LVM_VDO VG_VDO
  Logical volume "LVM_VDO" created.
[root@xxxxx566 ~]# mkfs.ext4 /dev/VG_VDO/LVM_VDO
[root@xxxxx566 ~]# mount /dev/VG_VDO/LVM_VDO /LVM_VDO/
[root@xxxxx566 ~]# cd /LVM_VDO/
[root@xxxxx566 LVM_VDO]# du -sh /LVM_VDO/
21G     /LVM_VDO/

VG Backup :

[root@xxxxx566 LVM_VDO]# vgcfgbackup -f /tmp/VG_VDO VG_VDO
  Volume group "VG_VDO" successfully backed up.

We have taken backup of "/etc/vdoconf.yml" and Volume Group cfg to remote server.

Exporting : Followed the below procedure to export Volume group and import after OS reinstallation.

[root@xxxxx566 tmp]# umount /LVM_VDO/

[root@xxxxx566 tmp]# vgchange -an VG_VDO
  0 logical volume(s) in volume group "VG_VDO" now active
[root@xxxxx566 tmp]# vgexport VG_VDO
  Volume group "VG_VDO" successfully exported
[root@xxxxx566 tmp]# pvscan
  PV /dev/mapper/VDO_STU1    is in exported VG VG_VDO [<500.00 GiB / 0    free]
  PV /dev/mapper/VDO_STU2    is in exported VG VG_VDO [<500.00 GiB / 0    free]
  PV /dev/sda2              VG vg_root         lvm2 [<278.88 GiB / <67.72 GiB free]
  Total: 3 [<1.25 TiB] / in use: 3 [<1.25 TiB] / in no VG: 0 [0 
  
Regards,
Sudhakar

**Comment by bgurney-rh** [comment]
I see; so the /etc/vdoconf.yml file is in place; however, the "Bad magic number" error from vdodumpconfig indicates that the VDO magic number was not found on the device '/dev/disk/by-id/dm-uuid-mpath-360060160253140004a3c0455be07e611'.

The VDO magic number is the string 'dmvdo001', occupying the first eight bytes of the block device on which "vdo create" was executed

```
# hexdump -C -s 0 -n 8 /dev/disk/by-id/dm-uuid-mpath-360060160253140004a3c0455be07e611
00000000  64 6d 76 64 6f 30 30 31                           |dmvdo001|
00000008
```

The "blkid" program can detect many different types of filesystems, as well as LVM2 headers, and so on.  Each filesystem, logical volume manager, and so on, has on-disk metadata that can be detected by blkid.

Can you run "blkid -p /dev/disk/by-id/dm-uuid-mpath-360060160253140004a3c0455be07e611" on this system?  There should be a "TYPE=" entry that indicates the type of metadata detected on the device.

**Comment by bgurney-rh** [comment]
It looks like the device /dev/disk/by-id/dm-uuid-mpath-360060160253140004a3c0455be07e611 has an msdos partition table.

When you run "lsblk", do you see any entries with TYPE "part" listed under the device /dev/disk/by-id/dm-uuid-mpath-360060160253140004a3c0455be07e611?

**Comment by bgurney-rh** [comment]
Also, if there are any "partitions" detected on this device, if you run "blkid -p" on those devices, what is the result?
