### ISSUE TITLE
vdo fails to build with target Fedora30 | In function 'logSystemCallErrno', return logWithStringError: '%s' directive argument is null

### ISSUE THREAD

**Issue by andreamtp** [dm-vdo/vdo#16]
When building vdo-6.2.1.48 with target Fedora 30, using gcc-9.1.1-1.fc30, the build fails with the following error

```
gcc` -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -g -O3 -fno-omit-frame-pointer -Wall -Wcast-align -Werror -Wextra -Winit-self -Wlogical-op -Wmissing-include-dirs -Wpointer-arith -Wredundant-decls -Wunused -Wwrite-strings   -DUDS_VERSION='"7.0.0.15"'  -I. -std=c99 -Wbad-function-cast -Wcast-qual -Wfloat-equal -Wformat=2 -Wmissing-declarations -Wmissing-format-attribute -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wswitch-default -pedantic    -c -MD -MF .deps/fileUtils.d.new -MP -MT fileUtils.o fileUtils.c -o fileUtils.o
In file included from fileUtils.c:36:
In function 'logSystemCallErrno',
    inlined from 'checkSystemCall' at syscalls.h:289:41,
    inlined from 'loggingFsync' at fileUtils.c:484:10,
    inlined from 'loggingFsync' at fileUtils.c:482:5,
    inlined from 'syncAndCloseFile' at fileUtils.c:149:16,
    inlined from 'trySyncAndCloseFile' at fileUtils.c:160:16:
syscalls.h:280:10: error: '%s' directive argument is null [-Werror=format-overflow=]
  280 |   return logWithStringError(((errno == EINTR) ? LOG_DEBUG : LOG_ERR),
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  281 |                             errno, "%s failed in %s", function, context);
      |                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

the exact command is:
`$ mock --rebuild -r fedora-30-x86_64 SRPMS/vdo-6.2.1.48-1.fc30.src.rpm`

[Full build logs from mock attached](https://github.com/dm-vdo/vdo/files/3229665/vdo-f30.tar.gz)

The issue also happen when building on copr:
[COPR building master](https://copr-be.cloud.fedoraproject.org/results/andreamtp/dm-vdo/fedora-30-x86_64/00915807-vdo/)

**Comment by rhawalsh** [comment]
I have applied the fixes our team has come up with to my own fork of this repo [0].  I've also updated my COPR repo [1] to be up to date for FC28 thru FCRawhide.

I believe we will be looking to post these fixes to this repo, but in the meantime I wanted them to be available.

[0] https://github.com/rhawalsh/vdo/tree/6.2.1.48_fixed-compiler-warning
[1] https://copr.fedorainfracloud.org/coprs/rhawalsh/dm-vdo/

**Comment by andreamtp** [comment]
> I have applied the fixes our team has come up with to my own fork of this repo [0]. I've also updated my COPR repo [1] to be up to date for FC28 thru FCRawhide.
> 
> I believe we will be looking to post these fixes to this repo, but in the meantime I wanted them to be available.

Excellent, thanks Andy!

**Comment by rhawalsh** [comment]
Closing this issue.  When we have more upstream-focused commits on this repo, the fix will be available directly from here.
