### ISSUE TITLE
Cant import snapshot volume with assigning new --uuid

### ISSUE THREAD

**Issue by MarcoR83** [dm-vdo/vdo#25]
```
vdo import --device=/dev/mapper/vdo-backup1-plain --uuid=7aabced1f66c413981c3fb89d8a1525a -n vdo1 --verbose
Importing VDO vdo1
vdodumpconfig /dev/mapper/vdo-backup1-plain
grep MemAvailable /proc/meminfo
dmsetup table --target vdo
vdodumpconfig /dev/disk/by-id/dm-uuid-CRYPT-LUKS2-692021079faf4089b9ae1db8b98e6964-vdo-plain
blkid -s UUID -o value /dev/dm-17
modprobe kvdo
vdosetuuid --uuid 7aabced1-f66c-4139-81c3-fb89d8a1525a /dev/disk/by-id/dm-uuid-CRYPT-LUKS2-692021079faf4089b9ae1db8b98e6964-vdo-backup1-plain
vdo: ERROR - Can't set the UUID for VDO volume vdo1; vdosetuuid: command failed, exit status 2
```

I cant find any binary or source-file called vdosetuuid in the 6.2.2.18 pre-release. Is there something missing or am I missing something?

**Comment by rhawalsh** [comment]
Hi @MarcoR83.  We'll take a look into why this wasn't included in the latest push.  I suspect something got missed on some of our tooling that left it out.

**Comment by MarcoR83** [comment]
thanks! Nice hat, btw. ;-)

**Comment by MarcoR83** [comment]
Hey there. I just installed the new  pre-release 6.2.2.24 , imported a LVM snapshot of my vdo-device with a random uuid, mounted the xfs-file-system inside it with -o nouuid and now running a backup. So I'm closing this issue.

**Comment by rhawalsh** [comment]
@MarcoR83, Thanks for confirming!  Please let us know if you have any other issues or questions.
