### ISSUE TITLE
Changing VDO to work with page granularity

### ISSUE THREAD

**Issue by sinashan** [dm-vdo/vdo#28]
Hey guys,

I want to change the code so that deduplication can be done in page level. I'm currently working on a small research project which aims to detect similarity at page level so I thought maybe I'd use VDO. Do any of you guys know if it's possible? And would you please guide me on where should I start cause I'm a bit running out of time.
Thanks

**Comment by mtsakai** [comment]
Could you clarify the details of what you are hoping to do? And also what page size you are targetting?

VDO operates at a 4K granularity, which is a typical page size for Linux systems. This choice informs many of the architectural decisions made in VDO. Using a larger or a smaller granularity would be possible, but it would be a fairly large undertaking. (I suspect it could be made to mostly work with enough time, but likely at a cost of performance or reliability that would be difficult to mitigate.)

If you are just looking to detect similarities between chunks of data, then you might look at the UDS index subsystem of VDO. Its interface is described in uds/uds.h. Adjusting the index to use a larger or smaller chunk size would be a much more tractable bit of work than adjusting all of VDO, and might be sufficient for your project.

**Comment by rhawalsh** [comment]
We have not seen a response in 4 weeks.  Closing this issue.
