### ISSUE TITLE
vdoformat.c:22:25: fatal error: blkid/blkid.h: No such file or dir

### ISSUE THREAD

**Issue by arendej** [dm-vdo/vdo#35]
Tried to run a make on this latest repo in CentOS7 with a 5.x kernel, and see this...
```
echo "Building vdoforcerebuild from vdoforcerebuild.o libuser.a ../base/libvdo.a ../../uds/libuds.a"
Building vdoforcerebuild from vdoforcerebuild.o libuser.a ../base/libvdo.a ../../uds/libuds.a
cc   vdoforcerebuild.o libuser.a ../base/libvdo.a ../../uds/libuds.a -ldl -pthread -lz -lrt -lm -luuid -o vdoforcerebuild
cc -fPIC -fpic -D_GNU_SOURCE -g -O3 -fno-omit-frame-pointer -Wall -Wcast-align -Werror -Wextra -Winit-self -Wlogical-op -Wmissing-include-dirs -Wpointer-arith -Wredundant-decls -Wunused -Wwrite-strings    -std=c99 -Wbad-function-cast -Wcast-qual -Wfloat-equal -Wformat=2 -Wmissing-declarations -Wmissing-format-attribute -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wswitch-default  -pedantic  -I../base -I../../uds -Wno-write-strings -DINTERNAL -DCURRENT_VERSION="\"6.2.3.114\""   -c -MMD -MF .deps/vdoformat.d.new -MP -MT vdoformat.o -ovdoformat.o vdoformat.c
vdoformat.c:22:25: fatal error: blkid/blkid.h: No such file or directory
 #include <blkid/blkid.h>
                         ^
compilation terminated.
make[3]: *** [vdoformat.o] Error 1
make[3]: Leaving directory `/root/tmp/vdo/utils/vdo/user'
make[2]: *** [all] Error 1
make[2]: Leaving directory `/root/tmp/vdo/utils/vdo'
make[1]: *** [all] Error 1
make[1]: Leaving directory `/root/tmp/vdo/utils'
make: *** [all] Error 1
```

**Comment by sweettea** [comment]
Hi funixz;

You need, I think, a package probably named libblkid-devel. 

Hope that helps!

Sweet Tea

**Comment by funixz** [comment]
Thanks! Now this... 
```
vdoformat.c: In function ‘checkForSignaturesUsingBlkid’:
vdoformat.c:298:9: error: ‘BLKID_SUBLKS_BADCSUM’ undeclared (first use in this function)
         BLKID_SUBLKS_BADCSUM);

```

**Comment by sweettea** [comment]
Hi! This is related to https://github.com/dm-vdo/vdo/pull/34 -- what version of blkid are you using? (`blkid --version`)

**Comment by funixz** [comment]
> Hi! This is related to #34 -- what version of blkid are you using? (`blkid --version`)

blkid from util-linux 2.23.2  (libblkid 2.23.0, 25-Apr-2013)

**Comment by sweettea** [comment]
Ah, yes, that would do it. Hopefully sometime soon we'll merge the patch in #34; in the meantime you could use a similar patch, or an older version of VDO.

**Comment by rhawalsh** [comment]
> Ah, yes, that would do it. Hopefully sometime soon we'll merge the patch in #34; in the meantime you could use a similar patch, or an older version of VDO.

I mentioned in the PR that @sweettea mentions that I have updated my fork to include the fix for this issue:

>Hello.  For now, I have integrated @jwieleRH's version of your PR into my fork at [Branch 6.2.3.114-COPR](https://github.com/rhawalsh/vdo/tree/6.2.3.114-COPR) using commit [35fce0549c67a05de884d4e810d779e281d82691](https://github.com/rhawalsh/vdo/commit/35fce0549c67a05de884d4e810d779e281d82691).  I have tested it on an EL7 host with a 5.8 kernel from elrepo, gcc 9.1.1 and blkid version 2.23.2-65.el7.

**Comment by funixz** [comment]
I'll have to git that a try, thanks @rhawalsh and @sweettea
