### ISSUE TITLE
Remove SVN tags

### ISSUE THREAD

**Issue by mureinik** [dm-vdo/vdo#4]
Most (all?) of the source files seem to have Subversion `$id` tags in them (e.g., in `Makefile`: `# $Id: //eng/vdo-releases/magnesium/src/packaging/src-dist/user/Makefile#1 $`). 

Presumably, the original development of VDO was done in SVN, but now that it's open-sourced in git, these tags could probably be removed.
I'd happily send such a patch if the project maintainers agree.

**Comment by jeredfloyd** [comment]
These are currently snapshot releases from an internal Perforce repo; we'll be cleaning this up as we prepare to change SCM and upstream. (Many moving parts, but we wanted to get this code out there under the new license for review and participation.)  Appreciate the offer, but the patch set would be moot.

BTW, this is an "alpha" snapshot of what is internally our "magnesium" release and will be updated over the coming months; we will be accepting (~backporting) pull requests and addressing issues raised as appropriate throughout that process.  Once Magnesium is done the work to upstreamwill begin in earnest.
