### ISSUE TITLE
Create VDO with more than one device???

### ISSUE THREAD

**Issue by gilbertoferreira** [dm-vdo/vdo#41]
How can we achieve this?
I just can see that --device flag accept one volume per vdo. Is that right??

Thanks

**Comment by rhawalsh** [comment]
Hi @gilbertoferreira,

Correct, --device must be only specified once and can only point at a block device.  If you want to aggregate multiple devices together, you will need to assemble something underneath such as an LVM stack, or MD RAID, or something else.

**Comment by gilbertoferreira** [comment]
> Hi @gilbertoferreira,
> 
> Correct, --device must be only specified once and can only point at a block device. If you want to aggregate multiple devices together, you will need to assemble something underneath such as an LVM stack, or MD RAID, or something else.

What if I use ZFS?? Should bring some advantage??

**Comment by rhawalsh** [comment]
Hi @gilbertoferreira,

I'm not sure.  That is not a configuration we test.  Is there a particular kind of functionality that you require for your system?

**Comment by gilbertoferreira** [comment]
> Hi @gilbertoferreira,
> 
> I'm not sure. That is not a configuration we test. Is there a particular kind of functionality that you require for your system?

Just wanna use more then one device in order to create some sort of RAID1 or RAID10... Something like that.

**Comment by Klaas-** [comment]
I think red hat recommends lvm+vdo for that kind of things https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/deduplicating_and_compressing_logical_volumes_on_rhel/index ; if you run zfs with compression and deduplication I don't think you'd need vdo
