### ISSUE TITLE
What is the role of VDO additional read-write BW?

### ISSUE THREAD

**Issue by Baimax-123** [dm-vdo/vdo#48]
I use the FIO tool for random writing and iostat to monitor the VDO volume and hard disk at the same time.
The VDO volume only has write BW, but there are both read and write BW in the hard disk (the approximate data is as follows: the read BW is the same as the write BW of the VDO volume, and the write BW is twice the write BW of the VDO volume).
Can you roughly describe the role of this additional bandwidth introduction?
As mentioned in the following table, VDO volumes are built directly on the hard disk.
The FIO write command is:
`sudo fio -filename=/dev/mapper/vdo_2 --bs=4k --output write4k.log --direct=1 --iodepth=128 --rw=randwrite --ioengine=libaio --buffer_compress_percentage=54 --buffer_compress_chunk=4096 --offset=0 --size=100% --runtime=50000s --time_based=1 --group_reporting --numjobs=4`
vdo_2 is the name.
Thanks.

**Comment by rhawalsh** [comment]
Hi @Baimax-123 I believe I just answered this in [this comment.](https://github.com/dm-vdo/vdo/issues/45#issuecomment-1119806811)

**Comment by Baimax-123** [comment]
Yes. And thanks for your answer.
