### ISSUE TITLE
"lvextend" command freezes my Debian 11(.3) server

### ISSUE THREAD

**Issue by tigerblue77** [dm-vdo/vdo#56]
Hello everyone,

Still working on my project to make VDO work on my Debian 11(.3), I'm testing on my production machine now and encountered a problem while extending a VDOPOOL and VDOdataLV, everything is detailed [here](https://www.reddit.com/r/linuxquestions/comments/uxhtnk/lvextend_freezes_my_debian_server/). I have not found a fix for the moment.

My problem description is a bit short because I don't really know which logs or screenshots I could show you, don't hesitate to ask. Thanks per advance !

**Comment by bjohnsto** [comment]
Hi Tigerblue77. My name is Bruce Johnston and I work on the VDO team. I'm looking into your issue but had a couple questions. First it appears, according to the logs you posted, that the VDO volume is 'dirty' as it is trying to rebuild the volume. I was wondering if you could give me some details as to what you might have been doing with the volume before trying to extend? Was this a brand new VDO LVM volume? 

I'd also like to get some general info on how big the volume was before and after resizing, and what parameters you used to create the volume, if possible.

Also I was wondering if you had tried lvresize vs lvextend and seen if there were any differences? 

Thanks in advance for your help.
Bruce

**Comment by bjohnsto** [comment]
> Thanks for taking a look at my issue. I see that you're hungry for informations and I will feed you as much as I can. Do not hesitate to ask any other question you would have or give me advice(s) if you see anything wrong. In my logs for example, I'm a bit worried by warnings like tools version not matching but I suppose that it's because of my LVM version ?
> 

I wouldn't worry about that at the moment. This issue should be solved with a future LVM update. I'm not sure if it is out yet, but should be soon.

> It was dirty because I brutally restarted from iDrac as it was frozen. I just tested a normal reboot and the "dirty" message is not present in logs
> 

Would you have any logs from before the crash? During the actual extend time and then the hang?

> 
> About resizing, the volume was initially 12GB then 1TB and then I added TB until now 12,1TB pool and 13,1TB VDOdataLV. FYI my VG is 21,8TB. I think the problem is not about the size and I would be able to reproduce it with any size. I think the problem is about IO, as discussed in Reddit thread.
> 

It could be. It certainly seems like you have some leads there. I'd be happy to wait on your testing there to see if that fixes issues. Let us know if you want to revisit this.

Thanks
Bruce

**Comment by tigerblue77** [comment]
Unable to reproduce problem with my new installation (KVDO v8.2.1.3 and VDO v8.2.0.2). Thanks for your help.
