### ISSUE TITLE
lvmvdo status config 

### ISSUE THREAD

**Issue by madmax01** [dm-vdo/vdo#58]
Hi everyone,

tried to have a look for the new vdo version.

so far to check config i done (pre 8.x)

vdo status  
or
vi /etc/vdoconf.yml

then i saw all the configs.

------------------------

when i do the LVM side

lvcreate --type vdo -n vdo0 -l+100%FREE  -V 1T  --metadataprofile vdo-custom  vg0/vdopool0

where is the lvm version of "vdo status" ?

vdostats --all /dev/mapper/vg0-vdopool0-vpool  = not seeing the config
lvmconfig --type full | grep vdo    =  not telling me the config of the vdo-custom i imported

Not finding atm the Info how to get the "allocation" for the created vdo

**Comment by madmax01** [comment]
Hi everyone,

why is there soo less focus on Github Issues????

would look forward if there is may just a short Info on this one please.

very less infos for new gen vdo

**Comment by rhawalsh** [comment]
Hi @madmax01,

@bjohnsto will take a look into this and get you some details on how to achieve what you're looking for.

**Comment by bjohnsto** [comment]
Hi @madmax01 I've talked a bit with the lvm folks and it seems there is info there, but perhaps not exactly the info you are looking for? Could you go into more detail as to what "allocation" you are looking for? The index size? The size of the VDO physical/logical size? Both? Something else?

**Comment by madmax01** [comment]
Hi everyone,

pre 8.x  "**vdo status**"

i was looking hows the Way for 8.x

i think i found infos in /etc/lvm/backup.... but a real lvm command as such i was not able to find.

Max

**Comment by madmax01** [comment]
thx for the Info ;)
