### ISSUE TITLE
VDO and IO write penalty

### ISSUE THREAD

**Issue by gorbyo** [dm-vdo/vdo#61]
Hi everyone.

I am trying to implement VDO in my project. I ran some tests for IOPS - FIO  tests on VDO device generated 100 IOPS

IOSTAT shows the following for write test
sdb (RAW dev): 300 iops
dm-5 (VDO dev): 100 iops

If I understand the results correctly, a Write IO penalty of 3 can be applied for VDO (like Write IO penalty for RAID)
But I didn't find any information about write IO penalty for VDO

Is it bug?

**Comment by gorbyo** [comment]
Look not a bug

**Comment by rhawalsh** [comment]
For the record, the discussion that we had about this can be found [here](https://listman.redhat.com/archives/vdo-devel/2022-July/000374.html).
